from enum import StrEnum


class TrustState(StrEnum):
    TRUSTED = "TRUSTED"
    REVIEW = "REVIEW"
    BLOCKED = "BLOCKED"


class IncidentState(StrEnum):
    HEALTHY = "HEALTHY"
    CONTEXT_CHANGED = "CONTEXT_CHANGED"
    BLOCKED = "BLOCKED"
    REMEDIATION_APPLIED = "REMEDIATION_APPLIED"
    RE_EVALUATED = "RE_EVALUATED"
    RESOLVED = "RESOLVED"


class AttestationState(StrEnum):
    TRUSTED = "TRUSTED"
    INVALIDATED = "INVALIDATED"
    BLOCKED = "BLOCKED"
    RE_EVALUATING = "RE_EVALUATING"
    RE_EVALUATED = "RE_EVALUATED"


class Decision(StrEnum):
    ALLOW = "ALLOW"
    REVIEW = "REVIEW"
    BLOCK = "BLOCK"


class DataMode(StrEnum):
    LIVE_DATAHUB = "LIVE_DATAHUB"
    LIVE_SEEDED_DATAHUB = "LIVE_SEEDED_DATAHUB"
    CACHED_DATAHUB = "CACHED_DATAHUB"
    SEEDED_DEMO = "SEEDED_DEMO"


class SourceSystem(StrEnum):
    DATAHUB = "DATAHUB"
    DATAHUB_MCP = "DATAHUB_MCP"
    AEGIS = "AEGIS"
    OPENAI = "OPENAI"
    BUSINESS_MCP = "BUSINESS_MCP"
    SEEDED_DATAHUB = "SEEDED_DATAHUB"
    SIMULATED_EXTERNAL = "SIMULATED_EXTERNAL"


class RunStatus(StrEnum):
    QUEUED = "QUEUED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    REVIEW = "REVIEW"


class RunStepType(StrEnum):
    RUN_STARTED = "RUN_STARTED"
    GOVERNANCE_EVIDENCE = "GOVERNANCE_EVIDENCE"
    CONTEXT_RETRIEVAL = "CONTEXT_RETRIEVAL"
    MODEL_RESPONSE = "MODEL_RESPONSE"
    TOOL_PROPOSED = "TOOL_PROPOSED"
    GATE_DECISION = "GATE_DECISION"
    TOOL_EXECUTED = "TOOL_EXECUTED"
    DATAHUB_WRITEBACK = "DATAHUB_WRITEBACK"
    RUN_COMPLETED = "RUN_COMPLETED"
    ERROR = "ERROR"


class GraphStatus(StrEnum):
    TRUSTED = "TRUSTED"
    CHANGED = "CHANGED"
    BLOCKED = "BLOCKED"
    REMEDIATED = "REMEDIATED"


class Relationship(StrEnum):
    DOWNSTREAM_OF = "DOWNSTREAM_OF"
    CONSUMES = "CONSUMES"
    USES_TOOL = "USES_TOOL"
    RELATED_DOCUMENT = "RELATED_DOCUMENT"
